name: compile keymaps

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  compile-keymaps:
    runs-on: ubuntu-latest
    container:
      image: jonz94/qmk_firmware
    steps:
      - uses: actions/checkout@v3

      # Planck
      - name: Copy planck directory
        run: cp -r ./planck /qmk_firmware/keyboards/planck/keymaps/jonz94

      - name: Compile planck's keymap
        run: qmk compile -kb planck/rev6 -km jonz94

      - name: Rename compiled file
        run: mv /qmk_firmware/planck_rev6_jonz94.bin /qmk_firmware/planck-rev6-jonz94.bin

      - name: Upload compiled file
        uses: actions/upload-artifact@v2
        with:
          name: planck rev6 keymap by jonz94
          path: /qmk_firmware/planck-rev6-jonz94.bin

      # Planck rev6 VIA
      - name: Copy planck-via directory
        run: cp -r ./planck-via /qmk_firmware/keyboards/planck/keymaps/via_jonz94

      - name: Compile planck's VIA keymap
        run: qmk compile -kb planck/rev6 -km via_jonz94

      - name: Rename compiled file
        run: mv /qmk_firmware/planck_rev6_via_jonz94.bin /qmk_firmware/planck-rev6-via-jonz94.bin

      - name: Upload compiled file
        uses: actions/upload-artifact@v2
        with:
          name: planck rev6's VIA by jonz94
          path: /qmk_firmware/planck-rev6-via-jonz94.bin

      # Preonic rev3 VIA
      - name: Copy preonic-via directory
        run: cp -r ./preonic-via /qmk_firmware/keyboards/preonic/keymaps/via_jonz94

      - name: Compile preonic's VIA keymap
        run: qmk compile -kb preonic/rev3 -km via_jonz94

      - name: Rename compiled file
        run: mv /qmk_firmware/preonic_rev3_via_jonz94.bin /qmk_firmware/preonic-rev3-via-jonz94.bin

      - name: Upload compiled file
        uses: actions/upload-artifact@v2
        with:
          name: preonic rev3's VIA by jonz94
          path: /qmk_firmware/preonic-rev3-via-jonz94.bin

      # zsa ergodox ez VIA
      - name: Copy ergodox-via directory
        run: cp -r ./ergodox-via /qmk_firmware/keyboards/ergodox_ez/keymaps/via_jonz94

      - name: Compile zsa ergodox ez's VIA keymap
        run: qmk compile -kb ergodox_ez -km via_jonz94

      - name: Rename compiled file
        run: mv /qmk_firmware/ergodox_ez_via_jonz94.hex /qmk_firmware/zsa-ergodox-ez-via-awpr.hex

      - name: Upload compiled file
        uses: actions/upload-artifact@v2
        with:
          name: ergodox ez's VIA by awpr
          path: /qmk_firmware/zsa-ergodox-ez-via-awpr.hex

      # dztech dz60rgb WKL v2 VIA
      - name: Copy dztech-dz60rgb-wkl-v2-via directory
        run: cp -r ./dztech-dz60rgb-wkl-v2-via /qmk_firmware/keyboards/dztech/dz60rgb_wkl/keymaps/via_jonz94

      - name: Compile dztech dz60rgb WKL v2's VIA keymap
        run: qmk compile -kb dztech/dz60rgb_wkl/v2 -km via_jonz94

      - name: Rename compiled file
        run: mv /qmk_firmware/dztech_dz60rgb_wkl_v2_via_jonz94.hex /qmk_firmware/dztech-dz60rgb-wkl-v2-via-jonz94.hex

      - name: Upload compiled file
        uses: actions/upload-artifact@v2
        with:
          name: dztech dz60rgb WKL v2's VIA by jonz94
          path: /qmk_firmware/dztech-dz60rgb-wkl-v2-via-jonz94.hex

      # dztech dz60rgb ANSI v2 VIA
      - name: Copy dztech-dz60rgb-ansi-v2-via directory
        run: cp -r ./dztech-dz60rgb-ansi-v2-via /qmk_firmware/keyboards/dztech/dz60rgb_ansi/keymaps/via_jonz94

      - name: Compile dztech dz60rgb WKL v2's VIA keymap
        run: qmk compile -kb dztech/dz60rgb_ansi/v2 -km via_jonz94

      - name: Rename compiled file
        run: mv /qmk_firmware/dztech_dz60rgb_ansi_v2_via_jonz94.hex /qmk_firmware/dztech-dz60rgb-ansi-v2-via-jonz94.hex

      - name: Upload compiled file
        uses: actions/upload-artifact@v2
        with:
          name: dztech dz60rgb WKL v2's VIA by jonz94
          path: /qmk_firmware/dztech-dz60rgb-ansi-v2-via-jonz94.hex

      # hineybush h60 VIA
      - name: Copy hineybush-h60-via directory
        run: cp -r ./hineybush-h60-via /qmk_firmware/keyboards/hineybush/h60/keymaps/via_jonz94

      - name: Compile hineybush h60's VIA keymap
        run: qmk compile -kb hineybush/h60 -km via_jonz94

      - name: Rename compiled file
        run: mv /qmk_firmware/hineybush_h60_via_jonz94.hex /qmk_firmware/hineybush-h60-via-jonz94.hex

      - name: Upload compiled file
        uses: actions/upload-artifact@v2
        with:
          name: hineybush h60's VIA by jonz94
          path: /qmk_firmware/hineybush-h60-via-jonz94.hex

      # idobao id75 v1 VIA
      - name: Copy idobao-id75-v1-via directory
        run: cp -r ./idobao-id75-v1-via /qmk_firmware/keyboards/idobao/id75/keymaps/via_jonz94

      - name: Compile id75's VIA keymap
        run: qmk compile -kb idobao/id75/v1 -km via_jonz94

      - name: Rename compiled file
        run: mv /qmk_firmware/idobao_id75_v1_via_jonz94.hex /qmk_firmware/idobao-id75-v1-via-jonz94.hex

      - name: Upload compiled file
        uses: actions/upload-artifact@v2
        with:
          name: idobao id75 v1's VIA by jonz94
          path: /qmk_firmware/idobao-id75-v1-via-jonz94.hex

      # plexus75
      - name: Copy plexus75-via directory
        run: cp -r ./plexus75-via /qmk_firmware/keyboards/checkerboards/plexus75/keymaps/via_jonz94

      - name: Compile plexus75's VIA keymap
        run: qmk compile -kb checkerboards/plexus75 -km via_jonz94

      - name: Rename compiled file
        run: mv /qmk_firmware/checkerboards_plexus75_via_jonz94.hex /qmk_firmware/plexus75-via-jonz94.hex

      - name: Upload compiled file
        uses: actions/upload-artifact@v2
        with:
          name: plexus75's VIA by jonz94
          path: /qmk_firmware/plexus75-via-jonz94.hex

      # plexus75 he
      - name: Copy plexus75-he-via directory
        run: cp -r ./plexus75-he-via /qmk_firmware/keyboards/checkerboards/plexus75_he/keymaps/via_jonz94

      - name: Compile plexus75 HE's VIA keymap
        run: qmk compile -kb checkerboards/plexus75_he -km via_jonz94

      - name: Rename compiled file
        run: mv /qmk_firmware/checkerboards_plexus75_he_via_jonz94.hex /qmk_firmware/plexus75-he-via-jonz94.hex

      - name: Upload compiled file
        uses: actions/upload-artifact@v2
        with:
          name: plexus75 HE's VIA by jonz94
          path: /qmk_firmware/plexus75-he-via-jonz94.hex

      # xd75
      - name: Copy xd75-via directory
        run: cp -r ./xd75-via /qmk_firmware/keyboards/xiudi/xd75/keymaps/via_jonz94

      - name: Compile xd75's VIA keymap
        run: qmk compile -kb xiudi/xd75 -km via_jonz94

      - name: Rename compiled file
        run: mv /qmk_firmware/xiudi_xd75_via_jonz94.hex /qmk_firmware/xd75-via-jonz94.hex

      - name: Upload compiled file
        uses: actions/upload-artifact@v2
        with:
          name: xd75's VIA by jonz94
          path: /qmk_firmware/xd75-via-jonz94.hex

      # Release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /qmk_firmware/planck-rev6-jonz94.bin
            /qmk_firmware/planck-rev6-via-jonz94.bin
            /qmk_firmware/preonic-rev3-via-jonz94.bin
            /qmk_firmware/zsa-ergodox-ez-via-awpr.hex
            ./ergodox-via/zsa-ergodox-ez-via-awpr.json
            /qmk_firmware/dztech-dz60rgb-wkl-v2-via-jonz94.hex
            /qmk_firmware/dztech-dz60rgb-ansi-v2-via-jonz94.hex
            /qmk_firmware/hineybush-h60-via-jonz94.hex
            /qmk_firmware/idobao-id75-v1-via-jonz94.hex
            /qmk_firmware/plexus75-via-jonz94.hex
            /qmk_firmware/plexus75-he-via-jonz94.hex
            ./plexus75-he-via/plexus75-he-via-npspears.json
            /qmk_firmware/xd75-via-jonz94.hex
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
